### ISSUE TITLE
Experimental?

### ISSUE THREAD

**Issue by Nicolab** [ysbaddaden/rome#1]
Hello Julien,

This ORM looks very well designed and nice to use. 
It seems experimental since 2 years, a development always sustained (last commit 27 days ago).

On the readme file it is indicated _exprimental_. Do you plan to go further than Experimental? :rocket:

**Comment by ysbaddaden** [comment]
Hey, I'm glad you're being interested. I don't have a use-case anymore, so I can't say whether it really works or not in reality, there are probably some bugs in a few places, and a lack of advanced features.

I'm maintaining it against recent Crystal updates, thought, because I really like it :)

**Comment by ysbaddaden** [comment]
I believe the API should stay stable. It's taken over the ActiveRecord patterns, and shouldn't change much.

Also associations have been left as a WIP in ~~an outdated~~ branch [feature/associations](https://github.com/ysbaddaden/rome/tree/feature/associations) ~~that should be rebased.~~

**Comment by Nicolab** [comment]
Ok I understand, thanks for your reply.
It's an enormous amount of work that has been done, especially for one person! :+1: 

Maybe this ActiveRecord pattern based on top of crystal-db would require less maintenance (more support for the low level). But if you don't have any more use cases, it would be a lot of work again without any real need. 
I will still follow this project from time to time, just in case :D

Edit: I have looked #2

**Comment by ysbaddaden** [comment]
Rome _is_ built on top of `DB` which implements the database-specific protocols. 

Rome::Adapter generate the database specific SQL queries from Rome query builders, and execute queries with Rome::Connection, taking some API discrepencies into account. For example Rome::Adapter::PostgreSQL will use `RETURNING id` whereas Rome::Adapter::MySQL will use DB's `#last_insert_id` method, same for escaping column names, values, declaring placeholders for prepared statements, ...

**Comment by Nicolab** [comment]
Ah yes! My eyes jumped right into the devs dependencies.
Thanks
